export { Dashboard } from './Dashboard';
export { InstitutionPage } from './InstitutionPage';
export { InstitutionsPage } from './InstitutionsPage';
export { TeachersPage } from './TeachersPage';
export { StudentsPage } from './StudentsPage';
export { ClassroomsPage } from './ClassroomsPage';
export { SchedulePage } from './SchedulePage';
export { SettingsPage } from './SettingsPage';
export { LoginPage } from './LoginPage';
export { TeacherDashboard } from './TeacherDashboard';
export { AttendancePage } from './AttendancePage';
export { GradesPage } from './GradesPage';
export { TeacherTimetablePage } from './TeacherTimetablePage';
export { AdminTimetablePage } from './AdminTimetablePage';
export { CoursesPage } from './CoursesPage';
export { TeacherRegisterPage } from './TeacherRegisterPage';
export { InstitutionRegisterPage } from './InstitutionRegisterPage';
export { EmailVerificationPage } from './EmailVerificationPage';
export { InstitutionDashboardPage } from './InstitutionDashboardPage';
export { AcceptInvitePage } from './AcceptInvitePage';
export { default as TeacherStudentsPage } from './TeacherStudentsPage';
export { default as TeacherClassesPage } from './TeacherClassesPage';
export { default as JoinTeacherPage } from './JoinTeacherPage';
export { default as TeacherStudentMgmtPage } from './TeacherStudentMgmtPage';
